[package]
name = "visualize-yew"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version="0.20", features=["csr"] }
web-sys = { version = "0.3.69", features = ["HtmlSelectElement", "HtmlDocument", "HtmlCanvasElement", "CanvasRenderingContext2d"]}
gloo = "0.11.0"
rand = "0.8.5"