name: Visualize Yew CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Run tests
      run: wasm-pack test --firefox --headless

  publish:
      needs: [tests]
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
        
